### ISSUE TITLE
Fix the loadash vulnerability

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/terribletester#2]
![image](https://user-images.githubusercontent.com/13623227/65779834-6a5ac180-e140-11e9-95e5-ea50b8c80cc0.png)

**Comment by DROOPER** [comment]
Hi, can I take this issue and fix it please for hacktoberfest? Thanks very much!

**Comment by haroon-sheikh** [comment]
Go ahead @DROOPER

**Comment by haroon-sheikh** [comment]
@DROOPER When working on this, make sure we're still able to generate the styles.

Run `gulp` to validate.
